In [2]:
import torch
import numpy as np


### 初始化张量

In [2]:
# 直接用数据创建，数据类型自动推断
data = [[4, 6, 7], [2, 7, 4]]
t1_data = torch.tensor(data,
                       device="cuda",
                       requires_grad=True)  # 该属性会记录梯度值信息，如果不设置，反向传播会没有梯度
print(t1_data)

tensor([[4, 6, 7],
        [2, 7, 4]])


In [3]:
# 从numpy数组创建
np_data = np.array(data)
t1_np=torch.from_numpy(np_data)
print(t1_np)

tensor([[4, 6, 7],
        [2, 7, 4]])


In [13]:
# 从另一个张量创建
t1_ones=torch.ones_like(t1_np)  # 保留源数据的属性(形状和数据类型),值变为1
print(t1_ones)
t1_rand=torch.rand_like(t1_np,dtype=torch.float)  # 会覆盖之前的数据，形状不变，数据变成0到1之间的浮点型
print(t1_rand)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.4887, 0.1744, 0.8066],
        [0.9912, 0.8698, 0.4745]])


In [16]:
# 创建随机值或者常量值，可通过shape指定形状，shape需要是一个数组
shape=(3,4)
t_rand=torch.rand(shape)
t_ones=torch.ones(shape)
t_zeros=torch.zeros(shape)

print(t_rand)
print(t_ones)
print(t_zeros)

tensor([[0.7893, 0.8119, 0.5694, 0.8201],
        [0.2856, 0.8608, 0.3524, 0.0169],
        [0.9965, 0.7266, 0.7276, 0.9687]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [17]:
# 其他创建方法
# 均匀分布
t1=torch.rand(5,5)
# 标准正态分布
t2=torch.randn(5,5)
# 离散正态分布
t3=torch.normal(mean=0.0,std=1.0,size=(5,5))
# 线性间隔向量(返回一维张量，包含start和end上均匀间隔的step个点)
t4=torch.linspace(start=-1,end=10,steps=10)
print(f"均匀分布{t1}\n标准正态分布{t2}\n离散正态分布{t3}\n线性间隔{t4}")

均匀分布tensor([[0.3207, 0.2002, 0.3376, 0.5144, 0.6966],
        [0.7474, 0.1974, 0.9884, 0.6000, 0.3422],
        [0.7919, 0.9962, 0.7407, 0.1317, 0.7073],
        [0.9457, 0.4631, 0.6441, 0.1591, 0.4266],
        [0.2363, 0.0873, 0.6378, 0.4015, 0.0761]])
标准正态分布tensor([[-0.2906, -0.8907, -0.7970,  0.1803, -1.4908],
        [-0.9400,  1.5824, -1.3060,  0.3925,  0.3021],
        [ 0.1791,  0.6606,  0.6363, -0.9073, -1.3009],
        [ 0.7817,  0.6059, -0.8554,  0.8660,  1.0193],
        [-0.3810,  0.6428,  0.1713, -0.0266,  0.1199]])
离散正态分布tensor([[-0.1575, -0.6616,  1.0440,  0.9712, -0.2390],
        [-1.4145, -1.0902, -0.0329,  0.1306,  1.3077],
        [-1.6729, -0.8652, -0.8887, -1.2437, -1.1711],
        [-0.7586,  0.0781, -0.0967, -0.0669,  0.7740],
        [ 0.1881, -1.5005, -1.6697, -0.7664,  2.0282]])
线性间隔tensor([-1.0000,  0.2222,  1.4444,  2.6667,  3.8889,  5.1111,  6.3333,  7.5556,
         8.7778, 10.0000])


In [19]:
# 张量的属性
print("张量的形状: ",t1.shape)  # 反回一个torch.Size对象
print("张量的数据类型: ",t1.dtype)
print("张量的存储设备: ",t1.device)
print("张量的尺寸大小: ",t1.size())  # 同t1.shape,但是这是方法需要带括号


张量的形状:  torch.Size([5, 5])
张量的数据类型:  torch.float32
张量的存储设备:  cpu
张量的尺寸大小:  torch.Size([5, 5])


### 张量运算

张量默认创建在cpu，一般在gpu运行快，可以通过.to("cuda")移动

**注意:** 跨设备移动大张量在时间和内存方面成本都很高 

In [20]:
tensor = torch.tensor(4)
if torch.cuda.is_available():  # 有cuda就返回true
    tensor = tensor.to('cuda')
print(tensor)

tensor(4, device='cuda:0')


In [40]:
# tensor索引和切片高度类似numpy
torch.manual_seed(0)  # 设置随机种子
tensor=torch.rand(4,4)
print(tensor)
print('第一行',tensor[0])
print('第一列',tensor[:,0])
print('最后一列',tensor[...,-1])


tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185]])
第一行 tensor([0.4963, 0.7682, 0.0885, 0.1320])
第一列 tensor([0.4963, 0.3074, 0.4556, 0.0223])
最后一列 tensor([0.1320, 0.8964, 0.4017, 0.5185])


In [45]:
# 拼接
t1=torch.ones(3,4)
t2=torch.zeros(3,4)
t3=torch.cat([t1,t2],dim=1)
t4=torch.cat([t1,t2])
print(t3)
print(t4)

tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
# 算术运算
# 点积运算
tensor=torch.tensor([[1.,2.,3.],[4.,5.,6.]])
t1=tensor@tensor.T
t2=tensor.matmul(tensor.T)
t3=torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=t3)  # 这种输出形状不匹配会报警告，提示以后将不支持
print(t1,t2,t3)

tensor([[14., 32.],
        [32., 77.]]) tensor([[14., 32.],
        [32., 77.]]) tensor([[14., 32.],
        [32., 77.]])


C:\Users\Administrator\AppData\Local\Temp\ipykernel_8728\2232807614.py:7: UserWarning: An output with one or more elements was resized since it had shape [2, 3], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Resize.cpp:35.)
  torch.matmul(tensor,tensor.T,out=t3)  # 这种输出形状不匹配会报警告，提示以后将不支持


In [51]:
# 可以用item将单元素张量转换为python数
t_sum=tensor.sum()
i=t_sum.item()
print(i,type(i))

21.0 <class 'float'>


In [5]:
# Inplace操作
#把计算结果存储到当前操作数中的操作就称为就地操作。含义和pandas中inPlace参数的含义一样。pytorch中，这些操作是由带有下划线_后缀的函数表示。例如：x.copy_(y),x.t_(), 将改变x自身的值。
# In-place操作虽然节省了一部分内存，但在计算导数时可能会出现问题，因为它会立即丢失历史记录。因此，不鼓励使用它们。
print(tensor)
tensor.add_(5)  # 加法，广播
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])


##### tensor 与 numpy之间的转换

CPU 和 NumPy 数组上的张量共享底层内存位置，所以改变一个另一个也会变。

In [3]:
# 张量到numpy数组
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [4]:
# Numpy数组到张量
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
